onboarding = false
[ui]
agent_panel_sort = "spaces"

show_agent_labels_on_pane_borders = true
status_indicators = "dots"
[keys]
prefix = "ctrl+g"

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer"
description = "open file viewer in split"

[[keys.command]]
key = "prefix+shift+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer-tab"
description = "open file viewer in tab"

[terminal]
default_shell = "/opt/homebrew/bin/fish"
shell_mode = "login"

[advanced]
scrollback_limit_bytes = 50000000

[ui.toast]
delivery = "herdr"
